#
# This is a Shiny web application. You can run the application by clicking
# the 'Run App' button above.
#
#
setwd("C:/Users/mattias.vesterlund/Desktop/BPA/CLL/CLL")

############### LIBRARIES
library(tidyverse)
library(MultiAssayExperiment)
library(ggbeeswarm)
library(ggpubr)
library(limma)
library(survival)
library(maxstat)
library(survminer)
library(RColorBrewer)
library(msigdbr)
library(clusterProfiler)
library(enrichplot)
############### DATA


load("multiomics_MAE.RData")

#download hallmarks end prep for enrichment
mdf = msigdbr(species = "Homo sapiens")%>% dplyr::filter(gs_cat == "H" |gs_cat == "C1" |gs_cat == "C2" |gs_cat == "C5" | gs_cat == "C6")
mt2g = mdf %>% dplyr::select(gs_name, gene_symbol) %>% as.data.frame()

#read in modularity clustering data generated by gephi 
moddf<-read.table("Modularityclusters.txt",header=T,sep="\t") #list of genesymbols and which modularity cluster they belong to
proteomics<-multiomics_MAE@ExperimentList@listData$proteomics
Background_symbols_vector<-rownames(proteomics)


cormat<-cor(t(proteomics), method=c("pearson"))
dim(cormat)



#### enrichment ####

completedf<-data.frame(unique(mdf$gs_name))
colnames(completedf)<-c("ID");
rownames(completedf)<-completedf$ID

comp_vec<-c("ID")
for (i in 1:6){
  alpha<-which(moddf$modularity_class==i); moddf_x<-(moddf[alpha,])
  cormat_modx<-subset(cormat,colnames(cormat)%in%moddf_x$Gene)
  gene_symbols_vector<-colnames(cormat_modx[,which(rowMax(t(cormat_modx))>0.7)])
  
  modxenrich_complete<-enricher(gene = gene_symbols_vector, universe=Background_symbols_vector, TERM2GENE = mt2g)
  cdf<-modxenrich_complete@result[,c(1,5)]
  completedf[rownames(cdf),i+1]<-cdf[2]
  
  Name1 <- paste( 'N-', print(i), sep = '.' )
  comp_vec[i+1]<-Name1; 
  print(i)
}

colnames(completedf)<-comp_vec
completedf2<-completedf[,2:7]
completedf2<-(-1)*log10(completedf2)

completedf2$enrichment_term<-rownames(completedf2)
completedf2[is.na(completedf2)]<-0
write.table(completedf2,file="enrichment-full.txt",quote=F,sep="\t")

##The full enrichment output was curated to remove redundant enrichments before visualization of p-values as a heatmap 

Enrichments<-read.table("selectedenrichment.txt",header=T,row.names=1,sep="\t")
Enrichments<-Enrichments[,1:6]
library(pheatmap)
pdf("enrichment-heatmap.pdf", onefile = TRUE,width=20,height=20)

pheatmap(Enrichments,color=gray.colors(256, start = 0, end = 1, gamma = 0.3, rev = TRUE),
         treeheight_row = 0, treeheight_col = 0,cellwidth=33,cellheight=11)
dev.off()
