---
title: "Analysis CLL Proteomics - Drugs"
author: "Sophie Rabe"
output:
  html_document:
    code_folding: hide
    toc: yes
    toc_depth: 3
    toc_float: yes
    df_print: paged
  word_document:
    toc: yes
    toc_depth: '4'
  pdf_document:
    toc: yes
    toc_depth: '4'
editor_options:
  chunk_output_type: console
---
Analysis date: `r Sys.Date()`

# Setup
## Load libraries
```{r load packages, message=FALSE, warning=FALSE}
library(plyr)
library(gtools)
library(pheatmap)
library(progress)
library(Matrix)
library(Hmisc)
library(ggpubr)
library(ggbeeswarm)
library(DESeq2)
library(tidyverse)
library(MultiAssayExperiment)
library(gplots)
library(RColorBrewer)
```

## Load data
```{r load data, message=FALSE}
source("data/Figure_layouts.R")
load("data/CLL_Proteomics_Setup.RData")
load("data/CLL_Proteomics_ConsensusClustering.RData")
```

```{r Add CCP group}
colData(multiomics_MAE)$PG <- as.factor(CCP_group5[rownames(colData(multiomics_MAE))])
colData(multiomics_MAE)$CCP6_RNA <- as.factor(CCP_group6_RNA[rownames(colData(multiomics_MAE))])
```


# Analysis
## Drug-drug correlations
```{r drug-drug cor}
drs_sel <- metadata(multiomics_MAE)$drugs_functional_groups %>% 
  filter( !( grepl("DMSO", Drug)   ) )  %>% 
  mutate(Pathways=if_else(Pathways=="Apoptosis", "Inducer/inhibitor of apoptosis", Pathways))

df_mean_drug_resp <- longFormat(multiomics_MAE[ , ,  "drug_resp_mono"]) %>% as_tibble() %>%
  separate(rowname, into = c("Drug", "Concentration_step"), sep = "_") %>%
  filter( !( grepl("DMSO", Drug)   ) )  %>% 
  group_by(primary, Drug) %>%
  dplyr::summarise(mean_percent_viable_cells = mean(value)) %>%
  ungroup() %>%
  spread(Drug, mean_percent_viable_cells) %>%
  column_to_rownames("primary") %>%
  as.matrix()

df_mean_drug_resp <- apply(df_mean_drug_resp, 2, function(z){
  if(any(is.na( z ))){
    z[is.na( z )] <- median(z, na.rm = TRUE)
  }
  return(z)
})

drug_cor_mat <- df_mean_drug_resp %>%
  cor() 
heatmap_drug_drug_cor <- pheatmap(drug_cor_mat,
         show_colnames = F,
         treeheight_row= 0,
         color = rev(brewer.pal(n = 11, name = "RdBu")),
         breaks = seq(-1,1,0.2),
         legend = F, border_color = NA,
         treeheight_col = 0,
         fontsize = 5
        )

heatmap_drug_drug_cor_legend <- pheatmap(drug_cor_mat,
         show_colnames = F,
         treeheight_row= 0,
         color = rev(brewer.pal(n = 11, name = "RdBu")),
         breaks = seq(-1,1,0.2), silent = TRUE
        )[[4]]$grobs[[4]]
```

## XPO
```{r proteomics and drug response XPO}
XPO_selinexor_plot_3 <- 
  wideFormat(multiomics_MAE[,,c("SNPs", "drug_resp_mono")][c("Selinexor_3" , "XPO1"),,] ) %>% 
  as_tibble() %>% 
  filter(primary %in% unname(unlist(colnames(multiomics_MAE[,,"proteomics"])))) %>%
    mutate_at(.vars =c("SNPs_XPO1"), as.logical ) %>%
    filter(!is.na(SNPs_XPO1 )) %>% 
  gather("cond", "Norm. percentage alive cells", c(-primary, -SNPs_XPO1 )) %>%
  mutate(cond=gsub("drug_resp_mono_", "", cond)) %>%
  separate(cond, into = c("drug", "conc"), sep = "_") %>%
  mutate(conc=paste("concentration", conc)) %>%
  ggplot(aes(SNPs_XPO1, `Norm. percentage alive cells`)) + 
  geom_boxplot(aes(fill= SNPs_XPO1)) + 
  geom_beeswarm() + 
  scale_fill_manual(values=c("#0571b0", "#ca0020")) +
  geom_hline(yintercept = 1, color="darkgrey") +
  pp_sra +
  scale_x_discrete(labels=c("FALSE"="wt", "TRUE"="mut")) +
  theme(axis.title.x = element_blank())

XPO_selinexor_plot_3 +  stat_compare_means(method = "wilcox") 
```

## Nutlin
```{r proteomics and drug response Nutlin}
TP53_Nutlin_plot_3 <- 
  wideFormat(multiomics_MAE[,,c("SNPs", "drug_resp_mono")][c("Nutlin 3a_3" , "TP53"),,] ) %>% 
  as_tibble() %>% 
    filter(primary %in% unname(unlist(colnames(multiomics_MAE[,,"proteomics"])))) %>%
  mutate_at(.vars =c("SNPs_TP53"), as.logical ) %>%
  filter(!is.na(SNPs_TP53 )) %>% 
  gather("cond", "Norm. percentage alive cells", c(-primary, -SNPs_TP53 )) %>%
  mutate(cond=gsub("drug_resp_mono_", "", cond)) %>%
  separate(cond, into = c("drug", "conc"), sep = "_") %>%
  mutate(conc=paste("concentration", conc)) %>%
  ggplot(aes(SNPs_TP53, `Norm. percentage alive cells`)) + 
  geom_boxplot(aes(fill= SNPs_TP53)) + 
  geom_beeswarm() + 
  scale_fill_manual(values=c("#0571b0", "#ca0020")) +
  geom_hline(yintercept = 1, color="darkgrey") +
  pp_sra +
  scale_x_discrete(labels=c("FALSE"="wt", "TRUE"="mut")) +
  theme(axis.title.x = element_blank())

TP53_Nutlin_plot_3 + stat_compare_means(method = "wilcox")
```

## Consensus cluster and drug response
### Boxplots specific drugs
```{r proteomics and drug response CCP sel, message=FALSE}
drugs_CCP_Duve_plot <- longFormat(multiomics_MAE[ ,,"drug_resp_mono"], colDataCols = "PG") %>% as_tibble() %>%
    filter(primary %in% unname(unlist(colnames(multiomics_MAE[,,"proteomics"])))) %>%
  filter(!is.na(PG)) %>%
  filter( !( grepl("DMSO", rowname)   ) )  %>% 
  filter(rowname %in% c( "Duvelisib_3")) %>%
  ggplot(aes( PG, value )) + 
  geom_boxplot(aes(fill=PG)) + 
  pp_sra + 
  scale_fill_manual(values = colors_CCP) +
  geom_beeswarm() +
  stat_compare_means(method = "wilcox", label="p.signif", label.y = 1.4, ref.group = ".all.", hide.ns = TRUE, size=5) +
  facet_wrap(~rowname, ncol = 5) +
  coord_cartesian(ylim = c(0,1.6)) +
  geom_hline(yintercept = 1, color="darkgrey") +
  ylab("Norm. percentage \n alive cells") + xlab("Proteomics groups (PG)")

drugs_CCP_Duve_plot + theme(aspect.ratio = 1) + guides(fill=FALSE) +
  stat_compare_means( label.y = 1.6)

drugs_CCP_Ibru_plot <- longFormat(multiomics_MAE[ ,,"drug_resp_mono"], colDataCols = "PG") %>% as_tibble() %>%
    filter(primary %in% unname(unlist(colnames(multiomics_MAE[,,"proteomics"])))) %>%
  filter(!is.na(PG)) %>%
  filter( !( grepl("DMSO", rowname)   ) )  %>% 
  filter(rowname %in% c( "Ibrutinib_2")) %>%
  ggplot(aes( PG, value )) + 
  geom_boxplot(aes(fill=PG)) + 
  pp_sra + 
  scale_fill_manual(values = colors_CCP) +
  geom_beeswarm() +
  stat_compare_means(method = "wilcox", label="p.signif", label.y = 1.4, ref.group = ".all.", hide.ns = TRUE, size=5) +
  facet_wrap(~rowname, ncol = 5) +
  coord_cartesian(ylim = c(0,1.6)) +
  geom_hline(yintercept = 1, color="darkgrey") +
  ylab("Norm. percentage \n alive cells") + xlab("Proteomics groups (PG)")

drugs_CCP_Ibru_plot + theme(aspect.ratio = 1) + guides(fill=FALSE) +
  stat_compare_means( label.y = 1.6)

drugs_CCP_Ide_plot <- longFormat(multiomics_MAE[ ,,"drug_resp_mono"], colDataCols = "PG") %>% as_tibble() %>%
    filter(primary %in% unname(unlist(colnames(multiomics_MAE[,,"proteomics"])))) %>%
  filter(!is.na(PG)) %>%
  filter( !( grepl("DMSO", rowname)   ) )  %>% 
  filter(rowname %in% c( "Idelalisib_3")) %>%
  ggplot(aes( PG, value )) + 
  geom_boxplot(aes(fill=PG)) + 
  pp_sra + 
  scale_fill_manual(values = colors_CCP) +
  geom_beeswarm() +
  stat_compare_means(method = "wilcox", label="p.signif", label.y = 1.4, ref.group = ".all.", hide.ns = TRUE, size=5) +
  facet_wrap(~rowname, ncol = 5) +
  coord_cartesian(ylim = c(0,1.6)) +
  geom_hline(yintercept = 1, color="darkgrey") +
  ylab("Norm. percentage \n alive cells") + xlab("Proteomics groups (PG)")

drugs_CCP_Ide_plot + theme(aspect.ratio = 1) + guides(fill=FALSE) +
  stat_compare_means( label.y = 1.6)

drugs_CCP_BAY_plot <- longFormat(multiomics_MAE[ ,,"drug_resp_mono"], colDataCols = "PG") %>% as_tibble() %>%
    filter(primary %in% unname(unlist(colnames(multiomics_MAE[,,"proteomics"])))) %>%
  filter(!is.na(PG)) %>%
  filter( !( grepl("DMSO", rowname)   ) )  %>% 
  filter(rowname %in% c( "BAY61-3606_2")) %>%
  ggplot(aes( PG, value )) + 
  geom_boxplot(aes(fill=PG)) + 
  pp_sra + 
  scale_fill_manual(values = colors_CCP) +
  geom_beeswarm() +
  stat_compare_means(method = "wilcox", label="p.signif", label.y = 1.4, ref.group = ".all.", hide.ns = TRUE, size=5) +
  facet_wrap(~rowname, ncol = 5) +
  coord_cartesian(ylim = c(0,1.6)) +
  geom_hline(yintercept = 1, color="darkgrey") +
  ylab("Norm. percentage \n alive cells") + xlab("Proteomics groups (PG)")

drugs_CCP_BAY_plot + theme(aspect.ratio = 1) + guides(fill=FALSE) +
  stat_compare_means( label.y = 1.6)

drugs_CCP_Selu_plot <- longFormat(multiomics_MAE[ ,,"drug_resp_mono"], colDataCols = "PG") %>% as_tibble() %>%
    filter(primary %in% unname(unlist(colnames(multiomics_MAE[,,"proteomics"])))) %>%
  filter(!is.na(PG)) %>%
  filter( !( grepl("DMSO", rowname)   ) )  %>% 
  filter(rowname %in% c( "Selumetinib_2")) %>%
  ggplot(aes( PG, value )) + 
  geom_boxplot(aes(fill=PG)) + 
  pp_sra + 
  scale_fill_manual(values = colors_CCP) +
  geom_beeswarm() +
  stat_compare_means(method = "wilcox", label="p.signif", label.y = 1.4, ref.group = ".all.", hide.ns = TRUE, size=5) +
  facet_wrap(~rowname, ncol = 5) +
  coord_cartesian(ylim = c(0,1.6)) +
  geom_hline(yintercept = 1, color="darkgrey") +
  ylab("Norm. percentage \n alive cells") + xlab("Proteomics groups (PG)")

drugs_CCP_Selu_plot + theme(aspect.ratio = 1) + guides(fill=FALSE) +
  stat_compare_means( label.y = 1.6)

drugs_CCP_Doxo_plot <- longFormat(multiomics_MAE[ ,,"drug_resp_mono"], colDataCols = "PG") %>% as_tibble() %>%
    filter(primary %in% unname(unlist(colnames(multiomics_MAE[,,"proteomics"])))) %>%
  filter(!is.na(PG)) %>%
  filter( !( grepl("DMSO", rowname)   ) )  %>% 
  filter(rowname %in% c("Doxorubicine_3")) %>%
  mutate(rowname = as.factor(rowname)) %>%
  ggplot(aes( PG, value )) + 
  geom_boxplot(aes(fill=PG)) + 
  scale_fill_manual(values = colors_CCP) +
  pp_sra + 
  geom_beeswarm() +
  stat_compare_means(method = "wilcox", label="p.signif", label.y = 1.4, ref.group = ".all.", hide.ns = TRUE, size=5) +
  facet_wrap(~rowname, ncol = 5) +
  coord_cartesian(ylim = c(0,1.6)) +
  geom_hline(yintercept = 1, color="darkgrey") +
  ylab("Norm. percentage \n alive cells") + xlab("Proteomics groups (PG)")

drugs_CCP_Doxo_plot + theme(aspect.ratio = 1) + guides(fill=FALSE) +
  stat_compare_means( label.y = 1.6)

drugs_CCP_Cyta_plot <- longFormat(multiomics_MAE[ ,,"drug_resp_mono"], colDataCols = "PG") %>% as_tibble() %>%
    filter(primary %in% unname(unlist(colnames(multiomics_MAE[,,"proteomics"])))) %>%
  filter(!is.na(PG)) %>%
  filter( !( grepl("DMSO", rowname)   ) )  %>% 
  filter(rowname %in% c("Cytarabine_2")) %>%
  mutate(rowname = as.factor(rowname)) %>%
  ggplot(aes( PG, value )) + 
  geom_boxplot(aes(fill=PG)) + 
  scale_fill_manual(values = colors_CCP) +
  pp_sra + 
  geom_beeswarm() +
  stat_compare_means(method = "wilcox", label="p.signif", label.y = 1.4, ref.group = ".all.", hide.ns = TRUE, size=5) +
  facet_wrap(~rowname, ncol = 5) +
  coord_cartesian(ylim = c(0,1.6)) +
  geom_hline(yintercept = 1, color="darkgrey") +
  ylab("Norm. percentage \n alive cells") + xlab("Proteomics groups (PG)")

drugs_CCP_Cyta_plot + theme(aspect.ratio = 1) + guides(fill=FALSE) +
  stat_compare_means( label.y = 1.6)

drugs_CCP_Flu_plot <- longFormat(multiomics_MAE[ ,,"drug_resp_mono"], colDataCols = "PG") %>% as_tibble() %>%
    filter(primary %in% unname(unlist(colnames(multiomics_MAE[,,"proteomics"])))) %>%
  filter(!is.na(PG)) %>%
  filter( !( grepl("DMSO", rowname)   ) )  %>% 
  filter(rowname %in% c( "Fludarabine_2")) %>%
  ggplot(aes( PG, value )) + 
  geom_boxplot(aes(fill=PG)) + 
  pp_sra + 
  scale_fill_manual(values = colors_CCP) +
  geom_beeswarm() +
  stat_compare_means(method = "wilcox", label="p.signif", label.y = 1.4, ref.group = ".all.", hide.ns = TRUE, size=5) +
  facet_wrap(~rowname, ncol = 5) +
  coord_cartesian(ylim = c(0,1.6)) +
  geom_hline(yintercept = 1, color="darkgrey") +
  ylab("Norm. percentage \n alive cells") + xlab("Proteomics groups (PG)")

drugs_CCP_Flu_plot + theme(aspect.ratio = 1) + guides(fill=FALSE) +
  stat_compare_means( label.y = 1.6)

drugs_CCP_proteasome_plot <- longFormat(multiomics_MAE[ ,,"drug_resp_mono"], colDataCols = "PG") %>% as_tibble() %>%
    filter(primary %in% unname(unlist(colnames(multiomics_MAE[,,"proteomics"])))) %>%
  filter(!is.na(PG)) %>%
  filter( !( grepl("DMSO", rowname)   ) )  %>% 
  filter(rowname %in% c("Carfilzomib_1", "Ixazomib_2")) %>%
  mutate(rowname = as.factor(rowname)) %>%
  mutate(rowname= factor(rowname, levels =c("Carfilzomib_1", "Ixazomib_2") )) %>%
  ggplot(aes( PG, value )) + 
  scale_fill_manual(values = colors_CCP) +
  geom_boxplot(aes(fill=PG)) + 
  pp_sra + 
  geom_beeswarm() +
  stat_compare_means(method = "wilcox", label="p.signif", label.y = 1.4, ref.group = ".all.", hide.ns = TRUE, size=5) +
  facet_wrap(~rowname, ncol = 1) +
  coord_cartesian(ylim = c(0,1.6)) +
  geom_hline(yintercept = 1, color="darkgrey") +
  ylab("Norm. percentage \n alive cells") + xlab("Proteomics groups (PG)") 

drugs_CCP_proteasome_plot + theme(aspect.ratio = 1) + guides(fill=FALSE) +
  stat_compare_means( label.y = 1.6)

 drugs_CCP_Ena_plot <- longFormat(multiomics_MAE[ ,,"drug_resp_mono"], colDataCols = "PG") %>% as_tibble() %>%
     filter(primary %in% unname(unlist(colnames(multiomics_MAE[,,"proteomics"])))) %>%
  filter(!is.na(PG)) %>%
  filter( !( grepl("DMSO", rowname)   ) )  %>% 
  filter(rowname %in% c( "Enasidenib_1")) %>%
  ggplot(aes( PG, value )) + 
  geom_boxplot(aes(fill=PG)) + 
  pp_sra + 
  scale_fill_manual(values = colors_CCP) +
  geom_beeswarm() +
  stat_compare_means(method = "wilcox", label="p.signif", label.y = 1.4, ref.group = ".all.", hide.ns = TRUE, size=5) +
  facet_wrap(~rowname, ncol = 5) +
  coord_cartesian(ylim = c(0,1.6)) +
  geom_hline(yintercept = 1, color="darkgrey") +
  ylab("Norm. percentage \n alive cells") + xlab("Proteomics groups (PG)")

drugs_CCP_Ena_plot + theme(aspect.ratio = 1) + guides(fill=FALSE) +
  stat_compare_means( label.y = 1.6)

 drugs_CCP_Thio_plot <- longFormat(multiomics_MAE[ ,,"drug_resp_mono"], colDataCols = "PG") %>% as_tibble() %>%
     filter(primary %in% unname(unlist(colnames(multiomics_MAE[,,"proteomics"])))) %>%
  filter(!is.na(PG)) %>%
  filter( !( grepl("DMSO", rowname)   ) )  %>% 
  filter(rowname %in% c( "Thioguanine_3")) %>%
  ggplot(aes( PG, value )) + 
  geom_boxplot(aes(fill=PG)) + 
  pp_sra + 
  scale_fill_manual(values = colors_CCP) +
  geom_beeswarm() +
  stat_compare_means(method = "wilcox", label="p.signif", label.y = 1.4, ref.group = ".all.", hide.ns = TRUE, size=5) +
  facet_wrap(~rowname, ncol = 5) +
  coord_cartesian(ylim = c(0,1.6)) +
  geom_hline(yintercept = 1, color="darkgrey") +
  ylab("Norm. percentage \n alive cells") + xlab("Proteomics groups (PG)")

drugs_CCP_Thio_plot + theme(aspect.ratio = 1) + guides(fill=FALSE) +
  stat_compare_means( label.y = 1.6)
```

### PG5 vs mean other groups
### Test drug response PG5 versus other groups
```{r proteomics and drug response PG5 test, message=FALSE}
df_for_ttest <- longFormat(multiomics_MAE[ ,,"drug_resp_mono"], colDataCols = "PG") %>% as_tibble() %>%
  filter(!is.na(PG)) %>%
  filter( !( grepl("DMSO", rowname)   ) )  %>% 
  mutate(PG5 = PG==5) 

pval_drs <- sapply( unique(df_for_ttest$rowname), function(dr){
  dr_other <- df_for_ttest %>%
    filter(rowname == dr, PG5 == FALSE) %>%
    .$value 
  dr_PG5 <- df_for_ttest %>%
    filter(rowname == dr, PG5 == TRUE) %>%
    .$value 
  test <- wilcox.test( dr_PG5, dr_other )
  return(c("p"= test$p.value, 
              "Difference percentage alive cells \nPG5 vs. all other groups"= mean(dr_PG5) - mean(dr_other)  ) )
}) %>% t %>% as.data.frame() %>% 
  rownames_to_column("Drug_c") %>% as_tibble()
pval_drs <- pval_drs %>%  
  mutate(FDR = p.adjust(p, method = "BH" )) %>% 
  separate(Drug_c , c("Drug", "c"), sep = "_")

volcano_PG5_drugs <- pval_drs %>%
  ggplot(aes(`Difference percentage alive cells \nPG5 vs. all other groups`, -log10(p) )) +
  geom_point(aes(color = FDR < 0.25 )) +
  #geom_text(data = pval_drs %>% filter(FDR < 0.25),
  #          aes(label = Drug_c,
  #              x= `Difference percentage alive cells \nPG5 vs. all other groups`+0.005), size= 2, hjust=0) +
  pp_sra +
  scale_color_manual(values = c("grey", colors_CCP[5] ))
volcano_PG5_drugs

pval_drs %>% arrange(FDR)
```

### Overview drug responses across PGs
```{r}
options(dplyr.summarise.inform = FALSE)
t.test_res_PGs_one <- 
  lapply(1:6, function(PG_sel){
    df_prep <- longFormat(multiomics_MAE[ ,,"drug_resp_mono"], colDataCols = "PG") %>% 
      as_tibble() %>%
      filter(!is.na(PG)) %>%
      filter( !( grepl("\\+|DMSO|SSZ|phenyleth|Oxaliplatin|Hydroxychloroquine|Obatoclax mesylate|Vitamin", rowname)     ) ) %>%
      mutate(Factor = PG == PG_sel) %>%
      separate(rowname, into = c("Drug", "conc"), sep = "_" ) 
    
    message(paste0("Evaluating PG", PG_sel ))
    pb <- progress_bar$new(total = length(unique(df_prep$Drug)))
    sapply(unique(df_prep$Drug), function(drug_sel){
      pb$tick()
      c_max_var <- df_prep %>%
        filter( Drug == drug_sel ) %>%
        group_by(conc) %>%
        summarise(sd_c = sd(value, na.rm = TRUE)  ) %>%
        arrange(desc(sd_c) ) %>%
        dplyr::slice(1) %>%
        .$conc
      mini_df <- df_prep %>%
        filter( Drug == drug_sel, conc == c_max_var, Factor ) 
      
      p <- t.test( mini_df$value, mu=1 )$p.value
      diff <-   1-mean(mini_df$value, na.rm=TRUE)
      return( c( PG = PG_sel, drug = drug_sel, p = p, diff = diff, conc_sel = c_max_var ))
    } ) %>%
      t %>%
      as_tibble() %>%
      mutate( p = as.numeric(p), diff = as.numeric(diff), PG = as.factor(PG)) %>%
      mutate(fdr = p.adjust(p, method = "fdr"))
    
  } ) %>% 
  bind_rows() #%>%
  #mutate( p = as.numeric(p), diff = as.numeric(diff), PG = as.factor(PG))

options(dplyr.summarise.inform = TRUE)

mx_PG_drugs_one <- t.test_res_PGs_one %>%
  dplyr::select(PG, drug, diff) %>%
  pivot_wider(names_from = PG, values_from = diff) %>%
  column_to_rownames("drug") %>%
  as.matrix() 
order_pheatmap_one <- pheatmap(mx_PG_drugs_one, cluster_cols = FALSE, silent = TRUE  ) 

response_PGs_to_drugs_FDR10 <- t.test_res_PGs_one %>%
  mutate(drug = as.factor(drug)) %>%
  mutate(drug = factor(drug, levels = rev(rownames(mx_PG_drugs_one)[order_pheatmap_one$tree_row$order] )) ) %>%
  mutate(dir= as.factor(sign(diff)*(-1) ) ) %>%
  mutate(p_cut= if_else(fdr > 0.1, 1, p)) %>%
  mutate(dir_cut = as.factor(if_else(fdr > 0.1, as.character(NA), as.character(dir) )  ) ) %>%
  ggplot(aes( PG, drug, 
              #alpha = 1-log10(p_cut), 
              alpha = abs(diff), 
              fill = dir_cut )) +
  geom_tile(color="grey") +
  scale_fill_manual(values= c("#0571b0", "#ca0020"), na.value = "white", labels= c("sensitive", "prosurvival", "below FDR\ncutoff of 10%")  ) +
  guides( alpha= guide_legend( "Effect size"), fill= guide_legend("Direction of\neffect") ) +
  pp_sra +
  theme(axis.title.y = element_blank()) 

```

# Save important plots
```{r save image}
save(
  drugs_CCP_proteasome_plot, 
  XPO_selinexor_plot_3, drugs_CCP_Doxo_plot, drugs_CCP_Duve_plot, 
     TP53_Nutlin_plot_3, drugs_CCP_Ide_plot, drugs_CCP_Ibru_plot, 
     drugs_CCP_Cyta_plot, 
     drugs_CCP_BAY_plot, drugs_CCP_Flu_plot, drugs_CCP_Selu_plot,
     heatmap_drug_drug_cor, heatmap_drug_drug_cor_legend,
     drugs_CCP_Ena_plot, 
  drugs_CCP_Thio_plot,
     volcano_PG5_drugs,
  response_PGs_to_drugs_FDR10,
file = "RData_plots/CLL_Proteomics_Drugs_Plots.RData")
```

# Session Info
```{r sessionInfo}
sessionInfo()
```
