---
title: "Analysis CLL Proteomics - Genetics"
author: "Sophie Rabe"
output:
  html_document:
    code_folding: hide
    toc: yes
    toc_depth: 3
    toc_float: yes
    df_print: paged
  word_document:
    toc: yes
    toc_depth: '4'
  pdf_document:
    toc: yes
    toc_depth: '4'
editor_options:
  chunk_output_type: console
---
Analysis date: `r Sys.Date()`

# Setup
## Load libraries
```{r load packages, message=FALSE, warning=FALSE}
library(plyr)
library(gtools)
library(pheatmap)
library(Matrix)
library(Hmisc)
library(ggpubr)
library(ggbeeswarm)
library(DESeq2)
library(tidyverse)
library(limma)
library(MultiAssayExperiment)
library(gplots)
```

## Load data
```{r load data, message=FALSE}
source("data/Figure_layouts.R")
load("data/CLL_Proteomics_Setup.RData")
load("data/CLL_Proteomics_ConsensusClustering.RData")
```

```{r Add CCP group}
colData(multiomics_MAE)$PG <- as.factor(CCP_group5[rownames(colData(multiomics_MAE))])
colData(multiomics_MAE)$CCP6_RNA <- as.factor(CCP_group6_RNA[rownames(colData(multiomics_MAE))])
```

# Analysis
## Associations of protein abundance with genetic alterations
## Wilcox test
### Function
```{r analysis proteomics ttest function,  eval=TRUE, echo=TRUE}
wilcox_proteins_any <- function(g, alteration, plot=FALSE, output=TRUE){
  if("SNPs" %in% (experiments(multiomics_MAE[alteration,,]) %>% names()) ){
    ty="SNPs_"}else if("chrom_abber" %in% (experiments(multiomics_MAE[alteration,,]) %>% names() ) ){
      ty="chrom_abber_"}else if("health_record_bin" %in% (experiments(multiomics_MAE[alteration,,]) %>% names() ) ){
        ty="health_record_bin_"}
  dat_g <- wideFormat(multiomics_MAE[c(g , alteration),,] ) %>% as_tibble() 
  dat_g <- dat_g %>% mutate(alt =as.logical(get(paste0(ty, alteration), envir=as.environment(dat_g))))
  
  if(grepl("ENSG", g)){
    assay_data="RNAseq_norm_"
    cap <- metadata(multiomics_MAE)$gene_symbol_mapping %>% filter(ensembl_gene_id==g) %>% .$hgnc_symbol
    col_b <- "#92c5de"
    col_r <- "#f4a582"
    cap_y <- paste("Transcript abundance", cap)
    }else{
    assay_data="proteomics_"
    cap <- g
    col_b <- "#0571b0"
    col_r <- "#ca0020"
    cap_y <- paste("Protein abundance", cap)
  }
  
  wt <- dat_g %>% filter(alt==0) %>% .[,paste0(assay_data, g)] %>% unlist
  mut <- dat_g %>% filter(alt==1) %>% .[,paste0(assay_data, g)] %>% unlist
  alt_lab <- alteration
  alt_lab <- gsub("_mutated", "", alt_lab)
  wt_lab <- "wt"
  mut_lab <- "mut"
  if(alt_lab=="IGHV"){
    wt_lab="U-CLL"
  mut_lab="M-CLL"}
  
  wx.test <- wilcox.test(wt, mut)
  if(plot==TRUE){
    p <- dat_g %>% filter(!is.na(alt )) %>% 
      ggplot(aes_string("alt", paste0(assay_data,g), fill="alt" )) + 
      geom_boxplot() + geom_beeswarm() + 
      xlab(alt_lab) +
      scale_x_discrete(labels=c(wt_lab, mut_lab)) +
      ylab(cap_y)+
      pp_sra + 
      scale_fill_manual(values = c(col_b,col_r)) 
      
    print(p+theme(aspect.ratio=2)+ theme(legend.position = 'none') +
      stat_compare_means(method = "wilcox", label = "p.signif", 
                         comparisons = list(c("TRUE","FALSE"))) )
    print(wx.test$p.value)
  }
  if(output==TRUE){return(c(g,  alteration, length(wt), length(mut), wx.test$p.value))
    }else if(all(plot==TRUE, output=="plot")){return(p)}
}
```

```{r analysis proteomics ttest, fig.height=4, fig.width=5, warning=FALSE, message=FALSE}
ZAP70_P_plot <- wilcox_proteins_any(g="ZAP70", plot = TRUE, output = "plot", alteration="IGHV_mutated")
ZAP70_R_plot <- wilcox_proteins_any(g="ENSG00000115085", plot = TRUE, output = "plot", alteration="IGHV_mutated")
ATM_P_plot <- wilcox_proteins_any(g="ATM", plot = TRUE, output = "plot", alteration="ATM")
ATM_R_plot <- wilcox_proteins_any(g="ENSG00000149311", plot = TRUE, output = "plot", alteration="ATM")
TP53_P_plot <- wilcox_proteins_any(g="TP53", plot = TRUE, output = "plot", alteration="TP53")
TP53_R_plot <- wilcox_proteins_any(g="ENSG00000141510", plot = TRUE, output = "plot", alteration="TP53")
SF3B1_P_plot <- wilcox_proteins_any(g="SF3B1", plot = TRUE, alteration="SF3B1", output = "plot")
XPO1_P_plot <- wilcox_proteins_any(g="XPO1", plot = TRUE, output = "plot", alteration="XPO1")
XPO1_R_plot <- wilcox_proteins_any(g="ENSG00000082898", plot = TRUE, output = "plot", alteration="XPO1")

IGHM_P_plot <- wilcox_proteins_any(g="IGHM", plot = TRUE, alteration="IGHV_mutated", output = "plot")
```


## Chromosome position and protein abundance
```{r analysis proteomics position chromosome tris12, fig.height=8, warning=FALSE, eval=TRUE, echo=TRUE}
plot_chromosome_theme <- list(
    coord_cartesian(ylim=c(-0.7,0.7)),
    facet_wrap(~paste("chromosome",chromosome_name), scales = "free_x"),
    ylab("log2 norm. protein abundance"),
    xlab("Location gene for protein on chromosome [bp]")
)
```

```{r analysis proteomics position chromosome, warning=FALSE, eval=TRUE, include=TRUE}
Chr12_P_plot <- proteomics_tbl_meta_biomart %>%
  filter( !is.na(value), !is.na(chrom_abber_trisomy12),
          chromosome_name %in% c("12")) %>%
  ggplot(aes(start_position, value, group=primary)) +
  geom_point(size=0.5, alpha=0.2, color="darkgrey") +
  stat_smooth(geom='line', alpha=0.5, se=FALSE, aes(color=chrom_abber_trisomy12), span=0.5, method = "loess") +
  plot_chromosome_theme +
  pp_sra +
  ggtitle("trisomy12") +
  geom_rect(xmin = 0, ymin=-0.68, ymax=0.68, xmax=133275309, color="gray40", size=1.5,  fill=NA) +
  scale_color_manual(values=c("#0571b0", "#ca0020"), name = "", 
                       labels = c("wt", "trisomy 12" ))
Chr12_P_plot +  theme(aspect.ratio=0.4, legend.position = 'none') 

Chr11_P_plot <- proteomics_tbl_meta_biomart %>%
  filter( !is.na(value), !is.na(chrom_abber_del11q),
          chromosome_name %in% c("11")) %>%
  ggplot(aes(start_position, value, group=primary)) +
  geom_point(size=0.5, alpha=0.2, color="darkgrey") +
  stat_smooth(geom='line', alpha=0.5, se=FALSE, aes(color=chrom_abber_del11q), span=0.5, method = "loess") +
  plot_chromosome_theme +
  pp_sra +
  ggtitle("del11q")+
  geom_rect(xmin = 97400000, ymin=-0.68, ymax=0.68, xmax=110600000, color="gray40", size=1.5,  fill=NA) +
  scale_color_manual(values=c("#0571b0", "#ca0020"), name = "", 
                       labels = c("wt","del11q"))
Chr11_P_plot + theme(aspect.ratio=0.4, legend.position = 'none') 

Chr13_P_plot <- proteomics_tbl_meta_biomart %>%
  filter( !is.na(value), !is.na(chrom_abber_del13q14),
          chromosome_name %in% c("13")) %>%
  ggplot(aes(start_position, value, group=primary)) +
  geom_point(size=0.5, alpha=0.2, color="darkgrey") +
  stat_smooth(geom='line', alpha=0.5, se=FALSE, aes(color=chrom_abber_del13q14), span=0.5, method = "loess") +
  plot_chromosome_theme +
  pp_sra +
  ggtitle("del13q")+
  geom_rect(xmin = 47000000,ymin=-0.68, ymax=0.68, xmax=51000000, color="gray40", size=1.5,  fill=NA) +
  scale_color_manual(values=c("#0571b0", "#ca0020"), name = "", 
                       labels = c("wt","del13q"))
Chr13_P_plot + theme(aspect.ratio=0.4, legend.position = 'none') 

message("In the region in which the deletion occurs (47Mb-51Mb, 2011 Ouillette et al.) the data are probably very noisy as the number of proteins we detected in the affected region is small:")
proteomics_tbl_meta_biomart %>%
  filter( !is.na(value), 
          chromosome_name %in% c("13"), start_position>47000000, start_position< 51000000) %>% dplyr::select(rowname) %>% unique() %>% nrow()

Chr17_P_plot <- proteomics_tbl_meta_biomart %>%
  filter( !is.na(value), !is.na(chrom_abber_del17p13 ),
          chromosome_name %in% c("17")) %>%
  ggplot(aes(start_position, value, group=primary)) +
  geom_point(size=0.5, alpha=0.2, color="darkgrey") +
  stat_smooth(geom='line', alpha=0.5, se=FALSE, aes(color=chrom_abber_del17p13), span=0.5, method = "loess") +
  plot_chromosome_theme +
  pp_sra +
  ggtitle("del17p")+
  geom_rect(xmin = 0, ymin=-0.68, ymax=0.68, xmax=10800000, color="gray40", size=1.5,  fill=NA) +
  scale_color_manual(values=c("#0571b0", "#ca0020"), name = "", 
                       labels = c("wt","del17p"))
Chr17_P_plot + theme(aspect.ratio=0.4, legend.position = 'none')  

Chr8_P_plot <- proteomics_tbl_meta_biomart %>%
  filter( !is.na(value), !is.na(chrom_abber_gain8q24 ),
          chromosome_name %in% c("8")) %>%
  ggplot(aes(start_position, value, group=primary)) +
  geom_point(size=0.5, alpha=0.2, color="darkgrey") +
  stat_smooth(geom='line', alpha=0.5, se=FALSE, aes(color=chrom_abber_gain8q24), span=0.5, method = "loess") +
  plot_chromosome_theme +
  pp_sra +
  ggtitle("gain8q24")+
  geom_rect(xmin = 117700001, ymin=-0.68, ymax=0.68, xmax=146364022, color="gray40", size=1.5,  fill=NA) +
  scale_color_manual(values=c("#0571b0", "#ca0020"), name = "", 
                       labels = c("wt","gain8q"))
Chr8_P_plot + theme(aspect.ratio=0.4, legend.position = 'none') 
```

## Chromosome position and RNA
### Creat df
```{r analysis RNA position chromosome tris12, fig.height=10, warning=FALSE, eval=TRUE, echo=TRUE}
plot_chromosome_theme_RNA <- list(
    #coord_cartesian(ylim=c(0.95,1.1)),
    coord_cartesian(ylim=c(0.95,1.05)),
    facet_wrap(~paste("chromosome",chromosome_name), scales = "free_x"),
    ylab("log10 norm. RNA counts"),
    xlab("Location gene on chromosome [bp]")
)

RNA_biomart<- left_join(
  left_join((longFormat(multiomics_MAE[,,"RNAseq_norm"] ) %>% as_tibble()), 
                                         metadata(multiomics_MAE)$gene_symbol_mapping[c(1,2,3,5:7)], 
                                         by=c("rowname"="ensembl_gene_id")),
  proteomics_tbl_meta_biomart_chrab, by=c("primary"))
RNA_biomart <- left_join( left_join(RNA_biomart,
          proteomics_tbl_meta_biomart_SNP, by=c("primary")),
          proteomics_tbl_meta_biomart_health, by=c("primary"))
```

### Normalise RNA to mean per gene
```{r}
RNA_biomart_mean <- RNA_biomart %>%
  group_by(rowname) %>%
  summarise( mean_value = mean(value, na.rm = TRUE) )

RNA_biomart <- left_join(
  RNA_biomart,
  RNA_biomart_mean ) %>%
  mutate(value = value/mean_value)
```

### Plot
```{r analysis RNA position chromosome, warning=FALSE, eval=TRUE, include=TRUE}
# Trisomy 12
Chr12_R_plot <- RNA_biomart %>%
  filter( !is.na(value), !is.na(chrom_abber_trisomy12),
          chromosome_name %in% c("12")) %>%
  ggplot(aes(start_position, value, group=primary)) +
  geom_point(size=0.5, alpha=0.2, color="darkgrey") +
  stat_smooth(geom='line', alpha=0.5, se=FALSE, aes(color=chrom_abber_trisomy12), span=0.5, method = "loess") +
  plot_chromosome_theme_RNA +
  pp_sra +
  ggtitle("trisomy12") +
  geom_rect(xmin = 0, ymin=0.95, ymax=1.05, xmax=133275309, color="gray40", size=1.5,  fill=NA) +    scale_color_manual(values=c("#92c5de", "#f4a582"), name = "", 
                       labels = c("wt","trisomy 12"))
Chr12_R_plot + theme(aspect.ratio=0.4, legend.position = 'none') 

# del11q
Chr11_R_plot <- RNA_biomart %>%
  filter( !is.na(value), !is.na(chrom_abber_del11q),
          chromosome_name %in% c("11")) %>%
  ggplot(aes(start_position, value, group=primary)) +
  geom_point(size=0.5, alpha=0.2, color="darkgrey") +
  stat_smooth(geom='line', alpha=0.5, se=FALSE, aes(color=chrom_abber_del11q), span=0.5, method = "loess") +
  plot_chromosome_theme_RNA +
  pp_sra +
  ggtitle("del11q")+
  geom_rect(xmin = 97400000, ymin=0.95, ymax=1.05, xmax=110600000, color="gray40", size=1.5,  fill=NA) +    
  scale_color_manual(values=c("#92c5de", "#f4a582"), name = "", 
                       labels = c("wt","del11q"))
Chr11_R_plot + theme(aspect.ratio=0.4, legend.position = 'none') 

# del13q
Chr13_R_plot <- RNA_biomart %>%
  filter( !is.na(value), !is.na( chrom_abber_del13q14),
          chromosome_name %in% c("13")) %>%
  ggplot(aes(start_position, value, group=primary)) +
  geom_point(size=0.5, alpha=0.2, color="darkgrey") +
  stat_smooth(geom='line', alpha=0.5, se=FALSE, aes(color=chrom_abber_del13q14), span=0.5, method = "loess") +
  plot_chromosome_theme_RNA +
  pp_sra +
  ggtitle("del13q")+
  geom_rect(xmin = 47000000, ymin=0.95, ymax=1.05, xmax=51000000, color="gray40", size=1.5,  fill=NA) +    
  scale_color_manual(values=c("#92c5de", "#f4a582"), name = "", 
                       labels = c("wt","del13q"))
Chr13_R_plot + theme(aspect.ratio=0.4, legend.position = 'none') 

# del17p
Chr17_R_plot <- RNA_biomart %>%
  filter( !is.na(value), !is.na(chrom_abber_del17p13),
          chromosome_name %in% c("17")) %>%
  ggplot(aes(start_position, value, group=primary)) +
  geom_point(size=0.5, alpha=0.2, color="darkgrey") +
  stat_smooth(geom='line', alpha=0.5, se=FALSE, aes(color=chrom_abber_del17p13), span=0.5, method = "loess") +
  plot_chromosome_theme_RNA +
  pp_sra +
  ggtitle("del17p")+
  geom_rect(xmin = 0, ymin=0.95, ymax=1.05, xmax=10800000, color="gray40", size=1.5,  fill=NA) + 
  scale_color_manual(values=c("#92c5de", "#f4a582"), name = "", 
                       labels = c("wt","del17p"))
Chr17_R_plot + theme(aspect.ratio=0.4, legend.position = 'none') 

Chr8_R_plot <- RNA_biomart %>%
  filter( !is.na(value), !is.na(chrom_abber_gain8q24),
          chromosome_name %in% c("8")) %>%
  ggplot(aes(start_position, value, group=primary)) +
  geom_point(size=0.5, alpha=0.2, color="darkgrey") +
  stat_smooth(geom='line', alpha=0.5, se=FALSE, aes(color=chrom_abber_gain8q24), span=0.5, method = "loess") +
  plot_chromosome_theme_RNA +
  pp_sra +
  ggtitle("gain8q24")+
  geom_rect(xmin = 117700001, ymin=0.95, ymax=1.05, xmax=146364022, color="gray40", size=1.5,  fill=NA) +    
  scale_color_manual(values=c("#92c5de", "#f4a582"), name = "", 
                       labels = c("wt","gain8q"))
Chr8_R_plot + theme(aspect.ratio=0.4, legend.position = 'none') 
```

# Save important plots
```{r save image}
save(ZAP70_P_plot, ZAP70_R_plot, TP53_P_plot, TP53_R_plot, ATM_P_plot, ATM_R_plot, Chr12_P_plot, Chr17_P_plot, 
     Chr12_R_plot, Chr17_R_plot, SF3B1_P_plot, XPO1_P_plot, XPO1_R_plot, Chr13_P_plot, Chr11_P_plot, 
     Chr13_R_plot, Chr11_R_plot, Chr8_P_plot,Chr8_R_plot, IGHM_P_plot, 
file = "RData_plots/CLL_Proteomics_Genetics_Plots.RData")
```

# Session Info
```{r sessionInfo}
sessionInfo()
```
