---
title: "Validation of IGHV - Trisomy 12 group with screen from Dietrich et al."
author: "Sophie Herbst"
output:
  html_document:
    code_folding: hide
    toc: yes
    toc_depth: 3
    toc_float: yes
    df_print: paged
  word_document:
    toc: yes
    toc_depth: '4'
  pdf_document:
    toc: yes
    toc_depth: '4'
editor_options:
  chunk_output_type: console
---
Analysis date: `r Sys.Date()`

# Setup
# Load libraries
```{r, message=FALSE, warning=FALSE}
library(tidyverse)
library(SummarizedExperiment)
library(BloodCancerMultiOmics2017)
library(survival)
library(survminer)
```

```{r}
source("data/Figure_layouts.R")
```

## Format data
```{r, message=FALSE}
lpdCLL <- lpdAll[, lpdAll$Diagnosis == "CLL"]

IGHV_tris12_TP53 <- left_join(
  left_join(enframe(exprs(lpdCLL)["trisomy12",], name = "PatID", value = "trisomy12" ),
            enframe(exprs(lpdCLL)["IGHV Uppsala U/M",], name = "PatID", value = "IGHV") ),
  enframe(exprs(lpdCLL)["TP53",], name = "PatID", value = "TP53" ) )


CLL_meta <- left_join(IGHV_tris12_TP53, 
          patmeta[ patmeta$Diagnosis == "CLL", ] %>% rownames_to_column("PatID") %>% dplyr::select(-IGHV)
          )

BCR_drug_IDs <- fData(lpdCLL) %>% rownames_to_column("ID") %>%
  filter(name %in% c("ibrutinib", "idelalisib", "duvelisib" ), subtype=="4:5" ) 

CLL_BCR <- left_join(CLL_meta,
          t(exprs(lpdCLL[BCR_drug_IDs$ID, ])) %>% as.data.frame() %>% rownames_to_column("PatID") )
colnames(CLL_BCR)[which(colnames(CLL_BCR) %in% BCR_drug_IDs$ID)] <- BCR_drug_IDs$name
CLL_BCR <- CLL_BCR %>% gather("drug", "viability", ibrutinib:duvelisib)
CLL_BCR <- 
  CLL_BCR %>%
  mutate(IGHV= as.factor(IGHV), trisomy12 = as.factor(trisomy12))

CLL_BCR_noTP53 <- CLL_BCR %>% filter(TP53 ==0)
CLL_BCR_noTP53 <- 
  CLL_BCR_noTP53 %>% 
  mutate(IGHV= as.factor(IGHV), trisomy12 = as.factor(trisomy12))
print(paste("Nr. of patients", unique(CLL_BCR_noTP53$PatID) %>% length() ))
```

# Analysis
## Drug response
```{r}
IC50_UCLL_BCR_drug <-  CLL_BCR_noTP53 %>%
  filter(IGHV==0, !is.na(trisomy12)) %>%
  ggplot(aes( trisomy12, viability, group = trisomy12 , fill= trisomy12) ) +
  geom_boxplot() + 
  ggbeeswarm::geom_beeswarm() +
  facet_grid(~drug) +
  pp_sra +
  scale_fill_manual(values = colors_CCP[c(4,2)] ) + 
  theme(legend.position = 'none')
IC50_UCLL_BCR_drug + stat_compare_means( label.y = 1.2,  hjust=0.26)+
        ylab("Mean viability \ntwo lowest concentrations")
```

## Survival
```{r}
  # Filter for patients with complete data
  df_surv <- CLL_BCR_noTP53 %>%
    filter(!is.na(IGHV), !is.na(trisomy12), !is.na(treatedAfter), !is.na(T5)) %>%
    dplyr::select(PatID, time=T5, status=treatedAfter, IGHV, trisomy12) %>%
    mutate(IGHV = if_else( IGHV ==0, "U-CLL",  "M-CLL" ), trisomy12 = if_else( trisomy12 == 0, "chr12 wt",  "trisomy12" ) ) %>%
    mutate(BinFactor = paste0(IGHV, " + ", trisomy12))
  
  fit <- survfit(Surv(time, status) ~ BinFactor, data = df_surv)

  ggsurvplot(fit, data = df_surv, 
             pval = TRUE, 
             pval.size = 4,
             pval.coord = c(2, 0.95),
             xlab = "Time in years",
             palette = colors_CCP[c(3, 1, 4, 2)],
             legend.labs = gsub("BinFactor=", "", names(fit$strata) ),
             legend.title = "",
             legend = "top",
             ggtheme = pp_sra,
             title= "TTT IGHV ~ trisomy12",
             ylab="Treatment free survival"
  ) 
  
  IC50_TTT <- ggsurvplot(fit, data = df_surv, 
             xlab = "Time in years",
             palette = colors_CCP[c(3, 1, 4, 2)],
             legend.labs = gsub("BinFactor=", "", names(fit$strata) ),
             legend.title = "",
             legend = "right",
             ggtheme = pp_sra,
             ylab="Treatment free survival"
  ) 
  
  # Survival for M-CLL patients
  df_surv <- CLL_BCR_noTP53 %>%
    filter(IGHV==1, !is.na(trisomy12), !is.na(treatedAfter), !is.na(T5)) %>%
    dplyr::select(PatID, time=T5, status=treatedAfter, IGHV, trisomy12) %>%
    mutate(BinFactor = trisomy12)
  
  fit <- survfit(Surv(time, status) ~ BinFactor, data = df_surv)
  
  ggsurvplot(fit, data = df_surv, 
             pval = TRUE, 
             pval.size = 4,
             pval.coord = c(2, 0.95),
             xlab = "Time in years",
             palette = c( "#0571b0", "#ca0020"),
             legend.labs = gsub("BinFactor=", "", names(fit$strata) ),
             legend.title = "Trisomy 12",
             legend = "top",
             ggtheme = pp_sra,
             title= "TTT M-CLL patients ~ trisomy12",
             ylab="Treatment free survival"
  ) 
  
  # Survival for U-CLL patients
  df_surv <- CLL_BCR_noTP53 %>%
    filter(IGHV==0, !is.na(trisomy12), !is.na(treatedAfter), !is.na(T5)) %>%
    dplyr::select(PatID, time=T5, status=treatedAfter, IGHV, trisomy12) %>%
    mutate(BinFactor = trisomy12)
  
  fit <- survfit(Surv(time, status) ~ BinFactor, data = df_surv)
  
  ggsurvplot(fit, data = df_surv, 
             pval = TRUE, 
             pval.size = 4,
             pval.coord = c(2, 0.95),
             xlab = "Time in years",
             palette = c( "#0571b0", "#ca0020"),
             legend.labs = gsub("BinFactor=", "", names(fit$strata) ),
             legend.title = "Trisomy 12",
             legend = "top",
             ggtheme = pp_sra,
             title= "TTT U-CLL patients ~ trisomy12",
             ylab="Treatment free survival"
  ) 
  
    # Survival M-CLL + tris12 patients vs U-CLL
  df_surv <- CLL_BCR_noTP53 %>%
    filter( !(IGHV==1 & trisomy12 ==0), !is.na(IGHV), !is.na(trisomy12), !is.na(treatedAfter), !is.na(T5)) %>%
    dplyr::select(PatID, time=T5, status=treatedAfter, IGHV, trisomy12) %>%
    mutate(BinFactor = IGHV)
  
  fit <- survfit(Surv(time, status) ~ BinFactor, data = df_surv)
  
  ggsurvplot(fit, data = df_surv, 
             pval = TRUE, 
             pval.size = 4,
             pval.coord = c(2, 0.95),
             xlab = "Time in years",
             palette = c( "#0571b0", "#ca0020"),
             legend.labs = gsub("BinFactor=", "", names(fit$strata) ),
             legend.title = "IGHV",
             legend = "top",
             ggtheme = pp_sra,
             title= "TTT M-CLL trisomy 12 patients vs. U-CLL",
             ylab="Treatment free survival"
  ) 
  
      # Survival for U-CLL patients
  df_surv <- CLL_BCR_noTP53 %>%
    filter( !is.na(IGHV), !is.na(trisomy12), !is.na(treatedAfter), !is.na(T5)) %>%
    dplyr::select(PatID, time=T5, status=treatedAfter, IGHV, trisomy12) %>%
    mutate(BinFactor = (IGHV==1 & trisomy12 ==0) )
  
  fit <- survfit(Surv(time, status) ~ BinFactor, data = df_surv)
  
  ggsurvplot(fit, data = df_surv, 
             pval = TRUE, 
             pval.size = 4,
             pval.coord = c(2, 0.95),
             xlab = "Time in years",
             palette = c( "#0571b0", "#ca0020"),
             legend.labs = gsub("BinFactor=", "", names(fit$strata) ),
             legend.title = "M-CLL without trisomy 12",
             legend = "top",
             ggtheme = pp_sra,
             title= "TTT M-CLL without trisomy 12 patients vs. other",
             ylab="Treatment free survival"
  ) 
  
```

# Save important plots
```{r save image}
save(  IC50_TTT,
       IC50_UCLL_BCR_drug,
file = "/Volumes/sd17b003/Sophie/Analysis/CLL_Proteomics/CLL_Proteomics_final/Robjects/CLL_Proteomics_IC50_validation_Plots.RData")
```

# Session Info
```{r sessionInfo}
sessionInfo()
```
